### ISSUE TITLE
MessagingStub_NodeJS: usage of that

### ISSUE THREAD

**Issue by jhamfler** [hftl-ims-research/wonder#18]
Introducing that [here](https://github.com/hftl-ims-research/wonder/blob/wondergui/src/stubs/tlabs/MessagingStub_NodeJS.js#L38) and using it [here](https://github.com/hftl-ims-research/wonder/blob/wondergui/src/stubs/tlabs/MessagingStub_NodeJS.js#L46) is unclear to me.

The usage of [that](https://github.com/hftl-ims-research/wonder/blob/wondergui/src/stubs/tlabs/MessagingStub_NodeJS.js#L107) on the other hand is clearly needed because [that](https://github.com/hftl-ims-research/wonder/blob/wondergui/src/stubs/tlabs/MessagingStub_NodeJS.js#L122) scope is different.

**Comment by sdruesedow** [comment]
"that" seems to be needed also in the first case, because "peers.forEach(..." opens a new scope where "that" is required to access the websocket.
